import { mkdir, readFile, rename, writeFile } from 'fs/promises';
import { dirname, join } from 'path';
import { homedir } from 'os';
import { expandHome } from './paths';
import type { IntegrationTarget } from './types';

export interface GenerateConfigInput {
  providerName: string;
  baseUrl: string;
  model: string;
  apiKeyEnvVar?: string;
  targetTool: IntegrationTarget;
  targetConfigPath?: string;
}

export interface GeneratedConfig {
  generatedConfigText: string;
  targetConfigPath: string;
  manualInstructions: string[];
  warnings: string[];
  canWriteAutomatically: boolean;
}

export interface WriteConfigInput extends GenerateConfigInput {
  dryRun?: boolean;
}

export interface WriteConfigResult extends GeneratedConfig {
  dryRun: boolean;
  written: boolean;
  backupPath?: string;
}

function defaultConfigPath(targetTool: IntegrationTarget): string {
  if (targetTool === 'codex') return join(homedir(), '.codex', 'config.toml');
  return join(homedir(), '.config', 'opencode', 'opencode.json');
}

export function generateOpenAICompatibleConfig(input: GenerateConfigInput): GeneratedConfig {
  const targetConfigPath = expandHome(input.targetConfigPath || defaultConfigPath(input.targetTool));
  const envVar = input.apiKeyEnvVar || 'OPENAI_API_KEY';
  const manualInstructions = [
    `Set ${envVar} in your shell environment before launching ${input.targetTool}.`,
    `Review ${targetConfigPath} before using it with ${input.providerName}.`,
    'Talocode stores API key environment variable names only; it does not write raw API keys.',
  ];
  const warnings = [
    'Dry run is recommended before writing config files.',
    'Existing files are backed up before Talocode writes generated config.',
  ];

  if (input.targetTool === 'codex') {
    return {
      targetConfigPath,
      canWriteAutomatically: true,
      manualInstructions,
      warnings,
      generatedConfigText: [
        '# Generated by Talocode. Review before use.',
        '[model_provider.talocode]',
        `name = "${escapeToml(input.providerName)}"`,
        `base_url = "${escapeToml(input.baseUrl)}"`,
        `env_key = "${escapeToml(envVar)}"`,
        '',
        '[profiles.talocode]',
        'model_provider = "talocode"',
        `model = "${escapeToml(input.model)}"`,
        '',
      ].join('\n'),
    };
  }

  return {
    targetConfigPath,
    canWriteAutomatically: true,
    manualInstructions,
    warnings,
    generatedConfigText: JSON.stringify(
      {
        $schema: 'https://opencode.ai/config.json',
        provider: {
          talocode: {
            npm: '@ai-sdk/openai-compatible',
            name: input.providerName,
            options: {
              baseURL: input.baseUrl,
              apiKey: `{env:${envVar}}`,
            },
            models: {
              [input.model]: {},
            },
          },
        },
      },
      null,
      2
    ),
  };
}

export async function writeOpenAICompatibleConfig(input: WriteConfigInput): Promise<WriteConfigResult> {
  const generated = generateOpenAICompatibleConfig(input);
  if (input.dryRun !== false) return { ...generated, dryRun: true, written: false };

  await mkdir(dirname(generated.targetConfigPath), { recursive: true });
  let backupPath: string | undefined;
  try {
    await readFile(generated.targetConfigPath, 'utf-8');
    backupPath = buildConfigBackupPath(generated.targetConfigPath);
    await rename(generated.targetConfigPath, backupPath);
  } catch {
    backupPath = undefined;
  }
  await writeFile(generated.targetConfigPath, generated.generatedConfigText, 'utf-8');
  return { ...generated, dryRun: false, written: true, backupPath };
}

export function buildConfigBackupPath(targetConfigPath: string, now = new Date()): string {
  return `${targetConfigPath}.talocode-backup-${timestamp(now)}`;
}

function timestamp(now = new Date()): string {
  return now.toISOString().replace(/[:.]/g, '-');
}

function escapeToml(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}
